#pragma once

static constexpr const char LB_RELEASE_PUBLIC_KEY_PEM[] = R"pem(
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0FOTjEUPd5BbkzRTzCSS
4TaB4tVlXgOFOOf7+aOosBJZhqypo/lFe+FKePV4GETFaLYEmwiajNz2kxzFUSGR
LP7DBIHAYmBZ280lTCARbjpzFlFLxO/eA22j18Ld6MjtrN4WbBntfeSVpWaDQyIM
ldgY4R4NY+Cd3Z0sUiCtwekDZ9i6AZGG1gjVhGcP0160SuaztLg2GVZ51Eq3fbYK
84peROMs3HODvrJXcKlaghIGMFRKDpXoujn7gAW8IBjaKB+ELBwamMPQeH4DahDw
NYy071BU+qcPYAW0rojmHL5IhVNWnHBDekiWIguvz0E8uweSujMnW0Ywx+mkg3cO
iwIDAQAB
-----END PUBLIC KEY-----
)pem";
